backend/controllers/ConnectivityIngredientsController.php
<?php

namespace backend\controllers;

use common\models\Dishes;
use common\models\Ingredients;
use Yii;
use common\models\ConnectivityIngredients;
use backend\models\ConnectivityIngredientsControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ConnectivityIngredientsController implements the CRUD actions for ConnectivityIngredients model.
 */
class ConnectivityIngredientsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ConnectivityIngredients models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ConnectivityIngredientsControl();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * @param $dishes_id
     * @return bool
     */
    public function actionGetUnselectedIngredient($dishes_id)
    {
        if (!empty($dishes_id)) {
            $ingredientsId = ConnectivityIngredients::find()
                ->select('ingredient_id')
                ->where(['dishes_id' => $dishes_id])
                ->asArray()
                ->all();

            if (!empty($ingredientsId)) {
                $ingredientsId = array_column($ingredientsId, 'ingredient_id');


                $ingredients = Ingredients::find()->select(['id', 'title'])
                    ->andWhere(['not',[ 'id'=> $ingredientsId]])
                    ->asArray()
                    ->all();

                if (!empty($ingredients)) {
                    foreach ($ingredients as $val) {
                        echo "<option value='{$val['id']}'>{$val['title']} </option>";
                    }
                } else {
                    return false;
                }
            } else {
                $ingredients = Ingredients::find()->select(['id', 'title'])
                    ->asArray()
                    ->all();

                if (!empty($ingredients)) {
                    foreach ($ingredients as $val) {
                        echo "<option value='{$val['id']}'>{$val['title']} </option>";
                    }
                }
            }

        }
    }

    /**
     * @param $dishes_id
     * @return bool
     */
    public function actionGetSelectedIngredient($dishes_id)
    {
        if (!empty($dishes_id)) {
            $ingredientsId = ConnectivityIngredients::find()
                ->select('ingredient_id')
                ->where(['dishes_id' => $dishes_id])
                ->asArray()
                ->all();

            if (!empty($ingredientsId)) {
                $ingredientsId = array_column($ingredientsId, 'ingredient_id');

                $ingredients = Ingredients::find()->select(['id', 'title'])
                    ->where(['id' => $ingredientsId])
                    ->asArray()
                    ->all();

                if (!empty($ingredients)) {
                    foreach ($ingredients as $val) {
                        echo "<option value='{$val['id']}'>{$val['title']} </option>";
                    }
                }
            }
            return true;
        }
        return false;
    }

    /**
     * Creates a new ConnectivityIngredients model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ConnectivityIngredients();

        if ($model->load(Yii::$app->request->post())) {


            $row = [];
            $ingredientsId = json_decode($model->ingredient_id);
            $dishes_id = $model->dishes_id;
            foreach ($ingredientsId as $val) {
                $row[] = [$dishes_id, $val
                ];
            }
            /**
             * delete old data
             */
            ConnectivityIngredients::deleteAll(['dishes_id' => $dishes_id]);

            $connectivityIngredients = Yii::$app->db->createCommand()
                ->batchInsert(
                    'connectivity_ingredients',
                    ['dishes_id', 'ingredient_id'],
                    $row
                )
                ->execute();
            if ($connectivityIngredients) {
                return $this->redirect(['index'], 301);
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);

    }



    /**
     * Deletes an existing ConnectivityIngredients model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ConnectivityIngredients model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ConnectivityIngredients the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ConnectivityIngredients::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/DishesController.php
<?php

namespace backend\controllers;

use Imagine\Image\Box;
use Yii;
use common\models\Dishes;
use backend\models\DishesControl;
use yii\imagine\Image;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * DishesController implements the CRUD actions for Dishes model.
 */
class DishesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Dishes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DishesControl();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Dishes model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Dishes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Dishes();

        if ($model->load(Yii::$app->request->post())) {
            $imgName = '';

            /* Upload Images */
            $imgFile = UploadedFile::getInstance($model, "img_name");

            if (!empty($imgFile)) {
                $imgPath = Yii::getAlias("@frontend") . "/web/images/dishes/";

                $imgName = Yii::$app->security->generateRandomString() . '.' . $imgFile->extension;
                $imgFile->saveAs($imgPath . $imgName);


                /**
                 * compress image, and  change size image
                 */
                $path = $imgPath . $imgName;
                $image = Image::getImagine()->open($path);

                $width = $image->getSize()->getWidth() >= 800 ? 800 : $image->getSize()->getWidth();
                $height = $image->getSize()->getHeight() >= 600 ? 600 : $image->getSize()->getWidth();

                $image->thumbnail(new Box($width, $height))
                    ->save($path, ['jpeg_quality' => 70])
                    ->save($path, ['png_compression_level' => 9]);


                /* small */

                $image = Image::getImagine()->open($path);

                $width = $image->getSize()->getWidth() >= 200 ? 200 : $image->getSize()->getWidth();
                $height = $image->getSize()->getHeight() >= 150 ? 150 : $image->getSize()->getWidth();

                $path = $imgPath . "small/" . $imgName;
                $image->thumbnail(new Box($width, $height))
                    ->save($path, ['jpeg_quality' => 40])
                    ->save($path, ['png_compression_level' => 9]);



            $model->img_name = $imgName;
        }
            if ($model->save()) {

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);

    }

    public function actionUploadImages($id)
    {
        $model = $this->findModel($id);

        $fullImgPath = Yii::getAlias("@frontend") . "/web/images/dishes/";

        if (!file_exists($fullImgPath)) {
            mkdir($fullImgPath, 0700);
        }
        if (!file_exists($fullImgPath . "small/")) {
            mkdir($fullImgPath . "small/", 0700);
        }

        $imgFile = UploadedFile::getInstance($model, "img_name");


        if (!empty($imgFile)) {

            if (!file_exists($fullImgPath . $model->img_name)) {
                unlink($fullImgPath . $model->img_name);
            }
            if (!file_exists($fullImgPath . "small/" . $model->img_name)) {
                unlink($fullImgPath . "small/" . $model->img_name);
            }

            $imgName = Yii::$app->security->generateRandomString() . '.' . $imgFile->extension;
            $imgFile->saveAs($fullImgPath . $imgName);


            /**
             * compress image, and  change size image
             */
            $path = $fullImgPath . $imgName;
            $image = Image::getImagine()->open($path);

            $width = $image->getSize()->getWidth() >= 800 ? 800 : $image->getSize()->getWidth();
            $height = $image->getSize()->getHeight() >= 600 ? 600 : $image->getSize()->getWidth();

            $image->thumbnail(new Box($width, $height))
                ->save($path, ['jpeg_quality' => 70])
                ->save($path, ['png_compression_level' => 9]);


            /* small */
            $image = Image::getImagine()->open($path);

            $width = $image->getSize()->getWidth() >= 200 ? 200 : $image->getSize()->getWidth();
            $height = $image->getSize()->getHeight() >= 150 ? 150 : $image->getSize()->getWidth();

            $path = $fullImgPath . "small/" . $imgName;
            $image->thumbnail(new Box($width, $height))
                ->save($path, ['jpeg_quality' => 40])
                ->save($path, ['png_compression_level' => 9]);


            $model->img_name = $imgName;
            if ($model->save(false)) {

                return true;
            }

        }
        return false;
    }

    public function actionDeleteFile($id)
    {

        $model = $this->findModel($id);

        if (!empty($model)) {

            $img_name = $model->img_name;
            $imgFullPath = Yii::getAlias("@frontend") . "/web/images/dishes/";


            if (file_exists($imgFullPath . $img_name)) {

                unlink($imgFullPath . $img_name);
            }
            if (file_exists($imgFullPath . "small/" . $img_name)) {
                unlink($imgFullPath . "small/" . $img_name);
            }
            $model->img_name = null;
            if ($model->save()) {

                return true;
            }
        }
        return false;
    }

    /**
     * Updates an existing Dishes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $oldImgName = $model->img_name;

        if ($model->load(Yii::$app->request->post())) {
            $imgFile = UploadedFile::getInstance($model, "img_name");


            if (!empty($imgFile)) {
                $fullImgPath = Yii::getAlias("@frontend") . "/web/images/dishes/";


                if (file_exists($fullImgPath . $model->img_name)) {

                    unlink($fullImgPath . $model->img_name);
                }
                if (file_exists($fullImgPath . "small/" . $model->img_name)) {
                    unlink($fullImgPath . "small/" . $model->img_name);
                }

                $imgName = Yii::$app->security->generateRandomString() . '.' . $imgFile->extension;
                $imgFile->saveAs($fullImgPath . $imgName);


                /**
                 * compress image, and  change size image
                 */
                $path = $fullImgPath . $imgName;
                $image = Image::getImagine()->open($path);

                $width = $image->getSize()->getWidth() >= 800 ? 800 : $image->getSize()->getWidth();
                $height = $image->getSize()->getHeight() >= 600 ? 600 : $image->getSize()->getWidth();

                $image->thumbnail(new Box($width, $height))
                    ->save($path, ['jpeg_quality' => 70])
                    ->save($path, ['png_compression_level' => 9]);


                /* small */
                $image = Image::getImagine()->open($path);

                $width = $image->getSize()->getWidth() >= 200 ? 200 : $image->getSize()->getWidth();
                $height = $image->getSize()->getHeight() >= 150 ? 150 : $image->getSize()->getWidth();

                $path = $fullImgPath . "small/" . $imgName;
                $image->thumbnail(new Box($width, $height))
                    ->save($path, ['jpeg_quality' => 40])
                    ->save($path, ['png_compression_level' => 9]);


                $model->img_name = $imgName;
            }
            $model->img_name = $oldImgName;
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('update', [
            'model' => $model,
        ]);

    }

    /**
     * Deletes an existing Dishes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Dishes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Dishes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Dishes::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/layouts/content.php
<?php

use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>ModuleOld</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <strong> All rights reserved.</strong>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-waring pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->

        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right"/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

backend/views/layouts/header.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
$userName = Yii::$app->user->identity['username'];
$homeUrl = Yii::$app->homeUrl;
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">DL</span><span class="logo-lg">Dishes Ingredients</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= $homeUrl ?>images/users/man.jpg" class="user-image" alt="User Image"/>
                        <span class="hidden-xs"><?= $userName ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="<?= $homeUrl ?>images/users/man.jpg" class="img-circle"
                                 alt="User Image"/>

                            <p>
                                <?= $userName ?>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="col-xs-4 text-center">
                                <a href="#">Followers</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Sales</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Friends</a>
                            </div>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <?= Html::a(
                                    'Sign out',
                                    ['/site/logout'],
                                    ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                ) ?>
                            </div>
                        </li>
                    </ul>
                </li>

                <!-- User Account: style can be found in dropdown.less -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

backend/views/layouts/left.php
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= Yii::$app->homeUrl ?>images/users/man.jpg" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?= Yii::$app->user->identity['username'] ?></p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
                <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat">
                    <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->

        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu'],
                'items' => [
                    ['label' => 'Menu Yii2', 'options' => ['class' => 'header']],
                    ['label' => 'Grid Sort', 'icon' => '', 'url' => ['/grid/grid-sort']],
                    ['label' => 'Connectivity Ingredients', 'icon' => '', 'url' => ['/connectivity-ingredients/index']],
                    ['label' => 'Dishes', 'icon' => '', 'url' => ['/dishes/index']],
                    ['label' => 'Ingredients', 'icon' => '', 'url' => ['/ingredients/index']],

                        ],
            ]
        ) ?>
    </section>
</aside>

backend/views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>