common/models/ConnectivityIngredients.php
<?php

namespace common\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "connectivity_ingredients".
 *
 * @property integer $id
 * @property integer $dishes_id
 * @property integer $ingredient_id
 *
 * @property Dishes $dishes
 * @property Ingredients $ingredient
 */
class ConnectivityIngredients extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'connectivity_ingredients';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

            [['dishes_id'], 'required'],
            [['dishes_id', 'ingredient_id'], 'integer'],
            [['dishes_id'], 'exist', 'skipOnError' => true, 'targetClass' => Dishes::className(), 'targetAttribute' => ['dishes_id' => 'id']],
            [['ingredient_id'], 'exist', 'skipOnError' => true, 'targetClass' => Ingredients::className(), 'targetAttribute' => ['ingredient_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'dishes_id' => 'Dishes ID',
            'ingredient_id' => 'Ingredient ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDishes()
    {
        return $this->hasOne(Dishes::className(), ['id' => 'dishes_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIngredient()
    {
        return $this->hasOne(Ingredients::className(), ['id' => 'ingredient_id']);
    }
}

backend/controllers/ConnectivityIngredientsController.php
<?php

namespace backend\controllers;

use common\models\Dishes;
use common\models\Ingredients;
use Yii;
use common\models\ConnectivityIngredients;
use backend\models\ConnectivityIngredientsControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ConnectivityIngredientsController implements the CRUD actions for ConnectivityIngredients model.
 */
class ConnectivityIngredientsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ConnectivityIngredients models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ConnectivityIngredientsControl();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * @param $dishes_id
     * @return bool
     */
    public function actionGetUnselectedIngredient($dishes_id)
    {
        if (!empty($dishes_id)) {
            $ingredientsId = ConnectivityIngredients::find()
                ->select('ingredient_id')
                ->where(['dishes_id' => $dishes_id])
                ->asArray()
                ->all();

            if (!empty($ingredientsId)) {
                $ingredientsId = array_column($ingredientsId, 'ingredient_id');


                $ingredients = Ingredients::find()->select(['id', 'title'])
                    ->andWhere(['not',[ 'id'=> $ingredientsId]])
                    ->asArray()
                    ->all();

                if (!empty($ingredients)) {
                    foreach ($ingredients as $val) {
                        echo "<option value='{$val['id']}'>{$val['title']} </option>";
                    }
                } else {
                    return false;
                }
            } else {
                $ingredients = Ingredients::find()->select(['id', 'title'])
                    ->asArray()
                    ->all();

                if (!empty($ingredients)) {
                    foreach ($ingredients as $val) {
                        echo "<option value='{$val['id']}'>{$val['title']} </option>";
                    }
                }
            }

        }
    }

    /**
     * @param $dishes_id
     * @return bool
     */
    public function actionGetSelectedIngredient($dishes_id)
    {
        if (!empty($dishes_id)) {
            $ingredientsId = ConnectivityIngredients::find()
                ->select('ingredient_id')
                ->where(['dishes_id' => $dishes_id])
                ->asArray()
                ->all();

            if (!empty($ingredientsId)) {
                $ingredientsId = array_column($ingredientsId, 'ingredient_id');

                $ingredients = Ingredients::find()->select(['id', 'title'])
                    ->where(['id' => $ingredientsId])
                    ->asArray()
                    ->all();

                if (!empty($ingredients)) {
                    foreach ($ingredients as $val) {
                        echo "<option value='{$val['id']}'>{$val['title']} </option>";
                    }
                }
            }
            return true;
        }
        return false;
    }

    /**
     * Creates a new ConnectivityIngredients model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ConnectivityIngredients();

        if ($model->load(Yii::$app->request->post())) {


            $row = [];
            $ingredientsId = json_decode($model->ingredient_id);
            $dishes_id = $model->dishes_id;
            foreach ($ingredientsId as $val) {
                $row[] = [$dishes_id, $val
                ];
            }
            /**
             * delete old data
             */
            ConnectivityIngredients::deleteAll(['dishes_id' => $dishes_id]);

            $connectivityIngredients = Yii::$app->db->createCommand()
                ->batchInsert(
                    'connectivity_ingredients',
                    ['dishes_id', 'ingredient_id'],
                    $row
                )
                ->execute();
            if ($connectivityIngredients) {
                return $this->redirect(['index'], 301);
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);

    }



    /**
     * Deletes an existing ConnectivityIngredients model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ConnectivityIngredients model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ConnectivityIngredients the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ConnectivityIngredients::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/connectivity-ingredients/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\widgets\Select2;
use common\models\Dishes;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\ConnectivityIngredients */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="connectivity-ingredients-form">

    <?php $form = ActiveForm::begin(); ?>

    <!--    --><? //= $form->field($model, 'dishes_id')->textInput() ?>
    <!--    --><? //= $form->field($model, 'ingredient_id')->textInput() ?>
    <div class="col-xs-12">

        <?php

        $dishes = ArrayHelper::map(Dishes::find()
            ->select(['id', 'title'])
            ->where(['is_status' => true])
            ->asArray()
            ->all(),
            'id', 'title');

        echo $form->field($model, 'dishes_id')->widget(Select2::classname(), [
            'data' => $dishes,
//            'disabled' => true,
            'options' => [
                'placeholder' => 'Dishes',
                'onChange' => '
                  
                            $.get("' . Url::toRoute(['/connectivity-ingredients/get-unselected-ingredient']) . '", { 
                            dishes_id: $(this).val() })
                                    .done(function(data){ 
                                        $(".unselected").html( data );
                                         });
                                         
                                         
                                         $.get("' . Url::toRoute(['/connectivity-ingredients/get-selected-ingredient']) . '", { 
                            dishes_id: $(this).val() })
                                    .done(function(data){ 
                                        $(".selected").html( data );
                                         });
                                         
                                         '
            ],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]);
        ?>
    </div>


    <div class="col-xs-12">
        <div class="form-group">
            <h2> Ingredient </h2>
            <?php echo maksyutin\duallistbox\Widget::widget([
                'model' => $model,
                'attribute' => 'ingredient_id',
                'title' => 'Ingredient',
                'data' => \common\models\Ingredients::find()->where(['is_status' => true]),

                'data_id' => 'id',
                'data_value' => 'title',
                'lngOptions' => [
                    'warning_info' => 'Are you sure you want to select this amount of items?',
                    'search_placeholder' => 'Filter',
                    'showing' => ' - showing',
                    'available' => 'Available',
                    'selected' => 'Selected'
                ]
            ]);
            ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/connectivity-ingredients/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\ConnectivityIngredientsControl */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="connectivity-ingredients-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'dishes_id') ?>

    <?= $form->field($model, 'ingredient_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/connectivity-ingredients/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\ConnectivityIngredients */

$this->title = 'Create Connectivity Ingredients';
$this->params['breadcrumbs'][] = ['label' => 'Connectivity Ingredients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="connectivity-ingredients-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/connectivity-ingredients/index.php
<?php

use yii\helpers\Html;
use  backend\modules\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ConnectivityIngredientsControl */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Connectivity Ingredients';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="connectivity-ingredients-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [

                'attribute' => 'dishes_id',
                'value' => function ($model) {
                     return $model['dishes']['title'];
                }
            ],
            [

                'attribute' => 'ingredient_id',
                'value' => function ($model) {
                     return $model['ingredient']['title'];
                }
            ],

            [
                'class' => \yii\grid\ActionColumn::className(),
                'template'=>'{delete}',
            ],
        ],
        'panel' => [
            'before' =>Html::a("<i class='fa fa-pencil' aria-hidden='true'></i> Update Connectivity Ingredients", ['create'], ['class' => 'btn btn-success'])
        ],

    ]); ?>
</div>